export const MUTATION_NUMBER_INCREMENT = 'MUTATION_NUMBER_INCREMENT'
export const ACTION_NUMBER_INCREMENT = 'ACTION_NUMBER_INCREMENT'

export const MUTATION_ADD_LIST = 'MUTATION_ADD_LIST'
export const ACTION_ADD_LIST = 'ACTION_ADD_LIST'
